// Generated by scripts/build_search_index.py — do not hand-edit.
window.SITE_SEARCH_INDEX = [
  {
    "url": "index.html#course-details",
    "page": "Home",
    "heading": "Course Details",
    "excerpt": "Instructor Jon Chun Schedule Tu/Th, 2:40\u20134:00 PM Location Timberlake #5 (Evans Conference Room)"
  },
  {
    "url": "index.html#quick-links",
    "page": "Home",
    "heading": "Quick Links",
    "excerpt": "Syllabus Schedule Assignments Policies About"
  },
  {
    "url": "core/about.html#course-description",
    "page": "About",
    "heading": "Course Description",
    "excerpt": "This upper-division course is a hands-on study of the AI frontier as it stands in late 2026. That frontier is no longer API plumbing or retrieval pipelines. It is AI software engineering (AI-SWE): coo\u2026"
  },
  {
    "url": "core/about.html#course-goals-and-learning-outcomes",
    "page": "About",
    "heading": "Course Goals and Learning Outcomes",
    "excerpt": "By the end of this course, students will be able to: Configure a professional, reproducible development environment (shell, terminal, dotfiles) suitable for agentic software engineering, with sound se\u2026"
  },
  {
    "url": "core/about.html#instructor",
    "page": "About",
    "heading": "Instructor",
    "excerpt": "Instructor Jon Chun Department Integrated Program for Humane Studies (IPHS) Office Hours Tu/Th, 1:30\u20132:30 PM, Timberlake #3, and by appointment Email is the best way to reach the instructor outside of\u2026"
  },
  {
    "url": "core/about.html#course-site",
    "page": "About",
    "heading": "Course Site",
    "excerpt": "Materials: https://github.com/jon-chun/theailab-net Quizzes, grades, and submissions: Moodle This syllabus continues the Frontiers in AI course offered since 2024."
  },
  {
    "url": "core/assignments.html#summary-of-assignments-and-weights",
    "page": "Assignments",
    "heading": "Summary of Assignments and Weights",
    "excerpt": "Assignment Weight Due Class Participation (incl. attendance and lightning presentation) 20% Ongoing Weekly Quizzes (lowest two dropped) 30% Weekly, in class Mini-Project 1 \u2014 Dev Environment (Pass/No-P\u2026"
  },
  {
    "url": "core/assignments.html#mini-project-1-development-environment-configuration",
    "page": "Assignments",
    "heading": "Mini-Project 1 \u2014 Development Environment Configuration",
    "excerpt": "5%, Pass/No-Pass. Due Friday, September 4. Configure a professional shell/terminal environment with documented customizations (e.g., zsh + .zprofile / .zshrc , XDG base directories, a modern CLI toolk\u2026"
  },
  {
    "url": "core/assignments.html#mini-project-2-ai-coding-agent-configuration",
    "page": "Assignments",
    "heading": "Mini-Project 2 \u2014 AI Coding Agent Configuration",
    "excerpt": "5%, Pass/No-Pass. Due Friday, September 25. High-level workflow pack. Package 3\u20135 reusable Claude Code customizations (Skills, a slash command, and/or a subagent) into a small project plugin a classma\u2026"
  },
  {
    "url": "core/assignments.html#mini-project-3-agent-harness-and-hooks",
    "page": "Assignments",
    "heading": "Mini-Project 3 \u2014 Agent Harness and Hooks",
    "excerpt": "10%, graded. Due Friday, October 23 (demos Tuesday, October 27). Low-level reliability harness. Add 3\u20135 lifecycle hooks so the agent formats, logs, injects repo state, or blocks dangerous commands whe\u2026"
  },
  {
    "url": "core/assignments.html#mini-project-4-swe-sdlc-best-practices-capstone",
    "page": "Assignments",
    "heading": "Mini-Project 4 \u2014 SWE/SDLC Best Practices Capstone",
    "excerpt": "10%, graded. Due Friday, November 20 (presentations Nov 17/19). Take a real-world, high-impact, non-trivial greenfield web application (instructor-supplied, or self-scoped and instructor-approved) fro\u2026"
  },
  {
    "url": "core/assignments.html#final-project",
    "page": "Assignments",
    "heading": "Final Project",
    "excerpt": "20%. Due exam period, December 14\u201318. An original interdisciplinary research project that puts the MP1\u20134 agent harness to work on a real research question of your choosing, applying at least one key t\u2026"
  },
  {
    "url": "core/assignments.html#alternative-format",
    "page": "Assignments",
    "heading": "Alternative Format",
    "excerpt": "Students who do not wish to publish their work publicly may instead complete a 3-hour written exam in lieu of the poster/portfolio requirement, covering the semester's technical and conceptual materia\u2026"
  },
  {
    "url": "core/assignments.html#final-project-requirements",
    "page": "Assignments",
    "heading": "Final Project Requirements",
    "excerpt": "Proposal: One-page proposal due Friday, November 13, approved by the instructor before substantial work begins. Poster: Professional research poster in Microsoft PowerPoint format ( .ppt / .pptx ), no\u2026"
  },
  {
    "url": "core/assignments.html#mini-project-3-4-grading-rubric",
    "page": "Assignments",
    "heading": "Mini-Project 3 & 4 Grading Rubric",
    "excerpt": "Each graded mini-project (MP3, MP4) is evaluated on: Criterion Weight What is assessed Functionality 15% Harness/workflow meets the specified requirements and performs as expected Technical Proficienc\u2026"
  },
  {
    "url": "core/policies.html#generative-ai-use-policy",
    "page": "Policies",
    "heading": "Generative AI Use Policy",
    "excerpt": "This course is about configuring and directing generative AI coding agents, so using them is the central subject matter, not a gray area. What remains non-negotiable is transparency and demonstrated u\u2026"
  },
  {
    "url": "core/policies.html#permitted-and-expected-ai-use-mini-projects-and-final-project-code",
    "page": "Policies",
    "heading": "Permitted and Expected AI Use (mini-projects and final project code)",
    "excerpt": "Writing, refactoring, and debugging code Planning and executing spec-driven development workflows Exploring concepts, generating examples, and drafting technical documentation Orchestrating subagents \u2026"
  },
  {
    "url": "core/policies.html#restricted-ai-use",
    "page": "Policies",
    "heading": "Restricted AI Use",
    "excerpt": "Weekly quizzes are closed-AI. No AI tools, devices, or notes during quizzes. Final Project poster prose must be human-written. AI may be used for brainstorming, outlining, feedback, and figure/code ge\u2026"
  },
  {
    "url": "core/policies.html#required-disclosure",
    "page": "Policies",
    "heading": "Required Disclosure",
    "excerpt": "All mini-projects and the final project must include a Generative AI Use Statement in the README (or poster) describing which AI tools/agents were used and how, including any harness/hooks/subagents c\u2026"
  },
  {
    "url": "core/policies.html#evaluation-criteria",
    "page": "Policies",
    "heading": "Evaluation Criteria",
    "excerpt": "Work is evaluated on demonstrated understanding of how the agentic system was configured and why, not on whether AI was used to produce it. A mini-project that works but whose author cannot explain th\u2026"
  },
  {
    "url": "core/policies.html#academic-integrity",
    "page": "Policies",
    "heading": "Academic Integrity",
    "excerpt": "Submitting a harness or workflow you cannot explain, misrepresenting what you configured versus what came from an unmodified template or tutorial, or using AI in ways that prevent you from demonstrati\u2026"
  },
  {
    "url": "core/policies.html#late-missing-work-policy",
    "page": "Policies",
    "heading": "Late/Missing Work Policy",
    "excerpt": "Late mini-project and final-project submissions are penalized 10% of the assignment grade per week (or portion thereof) past the deadline. Pass/No-Pass projects submitted late are treated as No-Pass u\u2026"
  },
  {
    "url": "core/policies.html#attendance-policy",
    "page": "Policies",
    "heading": "Attendance Policy",
    "excerpt": "Regular attendance is required. This is a seminar-style, project-based course where each session covers substantial and cumulative material. Attendance is part of the Participation grade. An unexcused\u2026"
  },
  {
    "url": "core/policies.html#student-work-and-external-sharing",
    "page": "Policies",
    "heading": "Student Work and External Sharing",
    "excerpt": "Mini-project repositories may be public or privately shared with the instructor, at each student's discretion. All external sharing of student work beyond the instructor is voluntary and opt-in, with \u2026"
  },
  {
    "url": "core/policies.html#secrets-hygiene-and-agent-safety",
    "page": "Policies",
    "heading": "Secrets Hygiene and Agent Safety",
    "excerpt": "This course has you publish configuration repositories and give coding agents real permissions on your own machine, so the following are course rules: Never commit API keys, tokens, or passwords to an\u2026"
  },
  {
    "url": "core/policies.html#college-statements-and-policies",
    "page": "Policies",
    "heading": "College Statements and Policies",
    "excerpt": ""
  },
  {
    "url": "core/policies.html#statement-on-academic-honesty",
    "page": "Policies",
    "heading": "Statement on Academic Honesty",
    "excerpt": "At Kenyon College we expect all students, at all times, to submit work that represents our highest standards of academic integrity. It is the responsibility of each student to learn and practice the p\u2026"
  },
  {
    "url": "core/policies.html#accessibility-accommodations",
    "page": "Policies",
    "heading": "Accessibility Accommodations",
    "excerpt": "Kenyon College values diversity and recognizes disability as an aspect of diversity. Our shared goal is to create learning environments that are accessible, equitable, and inclusive. If you anticipate\u2026"
  },
  {
    "url": "core/policies.html#title-ix-responsible-employee-statement",
    "page": "Policies",
    "heading": "Title IX / Responsible Employee Statement",
    "excerpt": "As a member of the Kenyon College faculty, I am concerned about the well-being and development of students, and am available to discuss any concerns. However, I want you to know that faculty members a\u2026"
  },
  {
    "url": "core/policies.html#wellbeing",
    "page": "Policies",
    "heading": "Wellbeing",
    "excerpt": "College is demanding and this course moves fast. If you are struggling, academically or otherwise, talk to me early. The Health and Counseling Center and your academic advisor are also there for you. \u2026"
  },
  {
    "url": "core/policies.html#copyright-of-course-materials",
    "page": "Policies",
    "heading": "Copyright of Course Materials",
    "excerpt": "Course materials created by the faculty instructor such as slide presentations, handouts, assignments, outlines, quizzes, tests, and classroom recordings are protected by copyright law. You may share \u2026"
  },
  {
    "url": "core/schedule.html#weeks-1-2-mini-project-1-development-environment-configuration",
    "page": "Schedule",
    "heading": "Weeks 1-2: Mini-Project 1 \u2014 Development Environment Configuration",
    "excerpt": "Week 1: Course Introduction Week 2: Shell Fundamentals and Dotfiles"
  },
  {
    "url": "core/schedule.html#weeks-3-5-mini-project-2-ai-coding-agent-configuration",
    "page": "Schedule",
    "heading": "Weeks 3-5: Mini-Project 2 \u2014 AI Coding Agent Configuration",
    "excerpt": "Week 3: Anatomy of an AI Coding Agent Week 4: CLAUDE.md and Slash Commands Week 5: Agent Skills, Subagents, and MCP"
  },
  {
    "url": "core/schedule.html#weeks-6-9-mini-project-3-agent-harness-and-hooks",
    "page": "Schedule",
    "heading": "Weeks 6-9: Mini-Project 3 \u2014 Agent Harness and Hooks",
    "excerpt": "Week 6: Hooks Architecture and Guardrails Week 7: Multi-Agent Orchestration Fundamentals Week 8: Comparative Agent Harnesses Week 9: Harness Integration and Debugging"
  },
  {
    "url": "core/schedule.html#weeks-10-13-mini-project-4-swe-sdlc-best-practices-capstone",
    "page": "Schedule",
    "heading": "Weeks 10-13: Mini-Project 4 \u2014 SWE/SDLC Best Practices Capstone",
    "excerpt": "Week 10: MP3 Demos and the Spec-Driven Development Landscape Week 11: GitHub as the AI-SDLC Hub Week 12: Observability, Cost, and Security Week 13: Full-Cycle Capstone Work Session and MP4 Presentatio\u2026"
  },
  {
    "url": "core/schedule.html#weeks-14-15-final-project-development-and-presentation",
    "page": "Schedule",
    "heading": "Weeks 14-15: Final Project Development and Presentation",
    "excerpt": "Week 14: Final Project Work Session and Poster Development Week 15: Final Project Poster Presentations"
  },
  {
    "url": "core/syllabus.html#course-details",
    "page": "Syllabus",
    "heading": "Course Details",
    "excerpt": "Instructor Jon Chun Department Integrated Program for Humane Studies (IPHS) Schedule Tu/Th, 2:40\u20134:00 PM Location Timberlake #5 (Evans Conference Room) Office Hours Tu/Th, 1:30\u20132:30 PM, Timberlake #3,\u2026"
  },
  {
    "url": "core/syllabus.html#course-description",
    "page": "Syllabus",
    "heading": "Course Description",
    "excerpt": "This upper-division course is a hands-on study of the AI frontier as it stands in late 2026. That frontier is no longer API plumbing or retrieval pipelines. It is AI software engineering (AI-SWE): coo\u2026"
  },
  {
    "url": "core/syllabus.html#course-goals-and-learning-outcomes",
    "page": "Syllabus",
    "heading": "Course Goals and Learning Outcomes",
    "excerpt": "By the end of this course, students will be able to: Configure a professional, reproducible development environment (shell, terminal, dotfiles) suitable for agentic software engineering, with sound se\u2026"
  },
  {
    "url": "core/syllabus.html#course-readings-and-materials",
    "page": "Syllabus",
    "heading": "Course Readings and Materials",
    "excerpt": "Textbooks: None required. Readings come from current documentation, engineering blog posts, research papers, and tooling repositories. They are updated weekly (the field moves that fast) and posted to\u2026"
  },
  {
    "url": "core/syllabus.html#hardware-and-operating-system",
    "page": "Syllabus",
    "heading": "Hardware and Operating System",
    "excerpt": "A laptop you can bring to every class session. Mini-Project 1 assumes a Unix-style shell (zsh). macOS or Linux are supported directly. Windows users must install WSL2 (Ubuntu) during Week 1 ; all shel\u2026"
  },
  {
    "url": "core/syllabus.html#required-accounts-and-subscriptions",
    "page": "Syllabus",
    "heading": "Required Accounts and Subscriptions",
    "excerpt": "Set these up during Week 1 using a personal (non-@kenyon.edu) email address , so your accounts and portfolio outlive your Kenyon login: Account Cost Purpose Personal Google (gmail.com) account Free Id\u2026"
  },
  {
    "url": "core/syllabus.html#secrets-hygiene-and-agent-safety-required-practice-for-all-projects",
    "page": "Syllabus",
    "heading": "Secrets Hygiene and Agent Safety (required practice for all projects)",
    "excerpt": "This course has you publish configuration repositories and give coding agents real permissions on your own machine, so the following are course rules: Never commit API keys, tokens, or passwords to an\u2026"
  },
  {
    "url": "core/syllabus.html#policy-on-changes-to-the-syllabus",
    "page": "Syllabus",
    "heading": "Policy on Changes to the Syllabus",
    "excerpt": "Given the pace of change in agentic AI tooling, this syllabus \u2014 especially the specific readings, tools, and technical references in the weekly schedule \u2014 may be updated during the semester. Core lear\u2026"
  },
  {
    "url": "core/syllabus.html#summary-of-assignments-and-weights",
    "page": "Syllabus",
    "heading": "Summary of Assignments and Weights",
    "excerpt": "Assignment Weight Due Class Participation (incl. attendance and lightning presentation) 20% Ongoing Weekly Quizzes (lowest two dropped) 30% Weekly, in class Mini-Project 1 \u2014 Dev Environment (Pass/No-P\u2026"
  },
  {
    "url": "core/syllabus.html#grading-scale",
    "page": "Syllabus",
    "heading": "Grading Scale",
    "excerpt": "Grade Percentage Description A 90\u2013100% Excellent B 80\u201389% Good C 70\u201379% Satisfactory D 60\u201369% Passing F Below 60% Failing Plus/minus grades are assigned within each band at the instructor's discretion\u2026"
  },
  {
    "url": "weeks/week-01.html",
    "page": "Week 1: Course Introduction",
    "heading": "Week 1: Course Introduction",
    "excerpt": "Thursday, August 27 \u2014 single session (Week 1 has no Tuesday class; the fall semester begins on Thursday, August 27). Part of Mini-Project 1 \u2014 Development Environment Configuration (Weeks 1\u20132). Course \u2026"
  },
  {
    "url": "weeks/week-02.html",
    "page": "Week 2: Shell Fundamentals and Dotfiles",
    "heading": "Week 2: Shell Fundamentals and Dotfiles",
    "excerpt": "Tuesday & Thursday, September 1 & 3 Part of Mini-Project 1 \u2014 Development Environment Configuration (Weeks 1\u20132). Shell fundamentals (zsh, .zprofile / .zshrc , XDG base directories), modern CLI toolkits\u2026"
  },
  {
    "url": "weeks/week-03.html",
    "page": "Week 3: Anatomy of an AI Coding Agent",
    "heading": "Week 3: Anatomy of an AI Coding Agent",
    "excerpt": "Tuesday & Thursday, September 8 & 10 Part of Mini-Project 2 \u2014 AI Coding Agent Configuration (Weeks 3\u20135). Anatomy of an AI coding agent; prompt engineering vs. context engineering; introduction to the \u2026"
  },
  {
    "url": "weeks/week-04.html",
    "page": "Week 4: CLAUDE.md and Slash Commands",
    "heading": "Week 4: CLAUDE.md and Slash Commands",
    "excerpt": "Tuesday & Thursday, September 15 & 17 Part of Mini-Project 2 \u2014 AI Coding Agent Configuration (Weeks 3\u20135). CLAUDE.md authoring (project + personal/global); custom slash commands. Lightning presentation\u2026"
  },
  {
    "url": "weeks/week-05.html",
    "page": "Week 5: Agent Skills, Subagents, and MCP",
    "heading": "Week 5: Agent Skills, Subagents, and MCP",
    "excerpt": "Tuesday & Thursday, September 22 & 24 Part of Mini-Project 2 \u2014 AI Coding Agent Configuration (Weeks 3\u20135). Agent Skills (authoring, structure, best practices); subagents; MCP as a complementary extensi\u2026"
  },
  {
    "url": "weeks/week-06.html",
    "page": "Week 6: Hooks Architecture and Guardrails",
    "heading": "Week 6: Hooks Architecture and Guardrails",
    "excerpt": "Tuesday & Thursday, September 29 & October 1 Part of Mini-Project 3 \u2014 Agent Harness and Hooks (Weeks 6\u20139). Hooks architecture (PreToolUse/PostToolUse/Stop and equivalents); wiring hooks to linting, te\u2026"
  },
  {
    "url": "weeks/week-07.html",
    "page": "Week 7: Multi-Agent Orchestration Fundamentals",
    "heading": "Week 7: Multi-Agent Orchestration Fundamentals",
    "excerpt": "Tuesday, October 6 only \u2014 single session (October Break falls Thursday\u2013Friday, October 8\u20139, so Week 7 has no Thursday class). Part of Mini-Project 3 \u2014 Agent Harness and Hooks (Weeks 6\u20139). Multi-agent \u2026"
  },
  {
    "url": "weeks/week-08.html",
    "page": "Week 8: Comparative Agent Harnesses",
    "heading": "Week 8: Comparative Agent Harnesses",
    "excerpt": "Tuesday & Thursday, October 13 & 15 Part of Mini-Project 3 \u2014 Agent Harness and Hooks (Weeks 6\u20139). Comparative agent harnesses (Claude Code, Codex CLI, Gemini CLI, OpenCode); FOSS extension ecosystem s\u2026"
  },
  {
    "url": "weeks/week-09.html",
    "page": "Week 9: Harness Integration and Debugging",
    "heading": "Week 9: Harness Integration and Debugging",
    "excerpt": "Tuesday & Thursday, October 20 & 22 Part of Mini-Project 3 \u2014 Agent Harness and Hooks (Weeks 6\u20139). Harness integration and debugging; FOSS-extension selection and integration work session. MP3 due Frid\u2026"
  },
  {
    "url": "weeks/week-10.html",
    "page": "Week 10: MP3 Demos and the Spec-Driven Development Landscape",
    "heading": "Week 10: MP3 Demos and the Spec-Driven Development Landscape",
    "excerpt": "Tuesday & Thursday, October 27 & 29 Part of Mini-Project 4 \u2014 SWE/SDLC Best Practices Capstone (Weeks 10\u201313). Tuesday: MP3 5-minute demos. Thursday: the spec-driven development landscape (GitHub Spec-K\u2026"
  },
  {
    "url": "weeks/week-11.html",
    "page": "Week 11: GitHub as the AI-SDLC Hub",
    "heading": "Week 11: GitHub as the AI-SDLC Hub",
    "excerpt": "Tuesday & Thursday, November 3 & 5 Part of Mini-Project 4 \u2014 SWE/SDLC Best Practices Capstone (Weeks 10\u201313). GitHub as the AI-SDLC hub: Actions/CI, PR workflows, branch conventions, agent-driven code r\u2026"
  },
  {
    "url": "weeks/week-12.html",
    "page": "Week 12: Observability, Cost, and Security",
    "heading": "Week 12: Observability, Cost, and Security",
    "excerpt": "Tuesday & Thursday, November 10 & 12 Part of Mini-Project 4 \u2014 SWE/SDLC Best Practices Capstone (Weeks 10\u201313). Observability, cost/token management, and security in production harnesses. Ethics thread:\u2026"
  },
  {
    "url": "weeks/week-13.html",
    "page": "Week 13: Full-Cycle Capstone Work Session and MP4 Presentations",
    "heading": "Week 13: Full-Cycle Capstone Work Session and MP4 Presentations",
    "excerpt": "Tuesday & Thursday, November 17 & 19 Part of Mini-Project 4 \u2014 SWE/SDLC Best Practices Capstone (Weeks 10\u201313). Full-cycle capstone work session (plan \u2192 decompose \u2192 implement \u2192 test \u2192 review \u2192 optional \u2026"
  },
  {
    "url": "weeks/week-14.html",
    "page": "Week 14: Final Project Work Session and Poster Development",
    "heading": "Week 14: Final Project Work Session and Poster Development",
    "excerpt": "Tuesday & Thursday, December 1 & 3 Part of Final Project (Weeks 14\u201315). Final project work session, applying the MP1\u20134 harness to the approved research question; poster development using the course te\u2026"
  },
  {
    "url": "weeks/week-15.html",
    "page": "Week 15: Final Project Poster Presentations",
    "heading": "Week 15: Final Project Poster Presentations",
    "excerpt": "Tuesday & Thursday, December 8 & 10 Part of Final Project (Weeks 14\u201315). Final Project poster presentations in class; Digital Release forms collected. Students taking the written-exam alternative are \u2026"
  }
];
