/* Client-side site search assistant. No network calls, no external API —
   matches typed queries against window.SITE_SEARCH_INDEX (generated by
   scripts/build_search_index.py) and links straight to the matching
   page/section. See tests/test_unit_html_structure.py's
   TestSiteSearchAssets for the guard keeping every page wired to this. */
(function () {
  "use strict";

  var INDEX = window.SITE_SEARCH_INDEX || [];
  var MAX_RESULTS = 8;

  function depthPrefix() {
    // index.html/404.html are at the root; core/ and weeks/ pages are one
    // level down, so index URLs ("core/x.html") need a "../" prefix there.
    return location.pathname.replace(/\/[^/]*$/, "/").match(/\/(core|weeks)\/$/)
      ? "../"
      : "";
  }

  function score(entry, terms) {
    var haystacks = [
      { text: entry.page.toLowerCase(), weight: 3 },
      { text: entry.heading.toLowerCase(), weight: 3 },
      { text: entry.excerpt.toLowerCase(), weight: 1 },
    ];
    var total = 0;
    terms.forEach(function (term) {
      haystacks.forEach(function (h) {
        if (h.text.indexOf(term) !== -1) total += h.weight;
      });
    });
    return total;
  }

  function search(query) {
    var terms = query.toLowerCase().trim().split(/\s+/).filter(Boolean);
    if (!terms.length) return [];
    return INDEX.map(function (entry) {
      return { entry: entry, score: score(entry, terms) };
    })
      .filter(function (r) {
        return r.score > 0;
      })
      .sort(function (a, b) {
        return b.score - a.score;
      })
      .slice(0, MAX_RESULTS)
      .map(function (r) {
        return r.entry;
      });
  }

  function build() {
    var prefix = depthPrefix();

    var button = document.createElement("button");
    button.type = "button";
    button.className = "site-search-toggle";
    button.setAttribute("aria-haspopup", "dialog");
    button.textContent = "Search this site";

    var overlay = document.createElement("div");
    overlay.className = "site-search-overlay";
    overlay.hidden = true;

    var panel = document.createElement("div");
    panel.className = "site-search-panel";
    panel.setAttribute("role", "dialog");
    panel.setAttribute("aria-modal", "true");
    panel.setAttribute("aria-label", "Search this site");

    var inputRow = document.createElement("div");
    inputRow.className = "site-search-input-row";

    var input = document.createElement("input");
    input.type = "search";
    input.className = "site-search-input";
    input.placeholder = "Search the syllabus, schedule, policies, weeks…";
    input.setAttribute("aria-label", "Search this site");

    var closeBtn = document.createElement("button");
    closeBtn.type = "button";
    closeBtn.className = "site-search-close";
    closeBtn.setAttribute("aria-label", "Close search");
    closeBtn.textContent = "×";

    inputRow.appendChild(input);
    inputRow.appendChild(closeBtn);

    var results = document.createElement("ul");
    results.className = "site-search-results";

    var hint = document.createElement("p");
    hint.className = "site-search-hint";
    hint.textContent = "Type to search — results link straight to the matching page or section.";

    panel.appendChild(inputRow);
    panel.appendChild(hint);
    panel.appendChild(results);
    overlay.appendChild(panel);

    document.body.appendChild(button);
    document.body.appendChild(overlay);

    function open() {
      overlay.hidden = false;
      document.body.classList.add("site-search-open");
      input.value = "";
      renderResults([]);
      hint.hidden = false;
      window.setTimeout(function () {
        input.focus();
      }, 0);
    }

    function close() {
      overlay.hidden = true;
      document.body.classList.remove("site-search-open");
      button.focus();
    }

    function renderResults(entries) {
      results.innerHTML = "";
      entries.forEach(function (entry) {
        var li = document.createElement("li");
        var a = document.createElement("a");
        a.href = prefix + entry.url;
        var pageSpan = document.createElement("span");
        pageSpan.className = "site-search-result-page";
        pageSpan.textContent =
          entry.page === entry.heading ? entry.page : entry.page + " › " + entry.heading;
        var excerptSpan = document.createElement("span");
        excerptSpan.className = "site-search-result-excerpt";
        excerptSpan.textContent = entry.excerpt;
        a.appendChild(pageSpan);
        a.appendChild(excerptSpan);
        li.appendChild(a);
        results.appendChild(li);
      });
    }

    button.addEventListener("click", open);
    closeBtn.addEventListener("click", close);
    overlay.addEventListener("click", function (e) {
      if (e.target === overlay) close();
    });
    document.addEventListener("keydown", function (e) {
      if (e.key === "Escape" && !overlay.hidden) close();
      if (e.key === "/" && overlay.hidden && document.activeElement.tagName !== "INPUT") {
        e.preventDefault();
        open();
      }
    });
    input.addEventListener("input", function () {
      var q = input.value;
      hint.hidden = q.trim().length > 0;
      var matches = search(q);
      renderResults(matches);
      if (q.trim() && !matches.length) {
        var li = document.createElement("li");
        li.className = "site-search-no-results";
        li.textContent = "No matches. Try a different word.";
        results.appendChild(li);
      }
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", build);
  } else {
    build();
  }
})();
